automation:
  - alias: "Elettrodomestici: notifiche media_players"
    id: media_players_elettrodomestici
    mode: queued
    variables:
      alexa: >
        {% from 'personal.jinja' import media_players %}
        {% set media = media_players('alexa_media').split() %}
        {{ media }}
      google: >
        {% from 'personal.jinja' import media_players %}
        {% set media = media_players('cast').split() %}
        {{ media }}
    trigger:
      - platform: event
        event_type: elettrodomestici
        event_data:
          media_player: "true"
    action:
      - alias: Imposta volume Notifica
        service: media_player.volume_set
        data:
          entity_id: "{{ expand(google + alexa) | map(attribute='entity_id') | list }}"
          volume_level: 0.5

      - alias: INVIA NOTIFICA
        parallel:
          - alias: Invia notifica ad Google
            if: "{{ google | count > 0 }}"
            then:
              - service: tts.google_translate_say
                data:
                  entity_id: "{{ google }}"
                  message: "{{ trigger.event.data.message | default('Messaggio elettrodomestico non impostato') }}"

          - alias: Invia notifica ad Alexa
            if: "{{ alexa | count > 0 }}"
            then:
              - service: notify.alexa_media
                data:
                  target: "{{ alexa }}"
                  data:
                    method: spoken
                  message: "{{ trigger.event.data.message | default('Messaggio elettrodomestico non impostato') }}"
